### ISSUE TITLE
Master branch gone?

### ISSUE THREAD

**Issue by JCCChris** [planetoftheweb/learnangular5#3]
I'm going through linked-in learning and there appears to be virtually nothing in the master branch.

**Comment by planetoftheweb** [comment]
I think this course was one of my experiments into the Github workflow. Usually the master branch has the finished project. The branches still have the status of each of the videos, so you should be good.

**Comment by JCCChris** [comment]
Would be helpful to modify the readme to that effect to avoid confusion.
